// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SalesTax.Models;

namespace SalesTax.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200602130152_Fixed_Image_Path")]
    partial class Fixed_Image_Path
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SalesTax.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discount")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.Property<string>("PhotoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductTaxCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("UnitPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 900,
                            Description = "Toyota Tacoma battery",
                            Discount = "10",
                            Name = "Battery",
                            PhotoPath = "/images/battery.png",
                            ProductTaxCode = "0",
                            Quantity = 1,
                            UnitPrice = "125.78"
                        },
                        new
                        {
                            Id = 910,
                            Description = "Goodyear X-300",
                            Discount = "15",
                            Name = "Tire",
                            PhotoPath = "/images/tire.png",
                            ProductTaxCode = "0",
                            Quantity = 4,
                            UnitPrice = "145.99"
                        },
                        new
                        {
                            Id = 905,
                            Description = "Dodge Ram Heavy Duty Strut set",
                            Discount = "5",
                            Name = "Struts",
                            PhotoPath = "/images/struts.png",
                            ProductTaxCode = "0",
                            Quantity = 1,
                            UnitPrice = "98.99"
                        },
                        new
                        {
                            Id = 934,
                            Description = "Silverado Air Filter",
                            Discount = "10",
                            Name = "Air Filter",
                            PhotoPath = "/images/airFilter.png",
                            ProductTaxCode = "0",
                            Quantity = 1,
                            UnitPrice = "38.55"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
